### ISSUE TITLE
Customize logging

### ISSUE THREAD

**Issue by mini-ninja-64** [sytsereitsma/mdbook-plantuml#45]
I would like to configure the logging to output to stderr so it can be captured in logs without having to record a seperate output.log file

This made me think maybe it would be better to add support for the `log4rs` configuration files.

Would this be an acceptable pull request to raise against the project?

**Comment by sytsereitsma** [comment]
Thanks. What would you think about adding the logging into the rendered pages/code blocks?

**Comment by mini-ninja-64** [comment]
Thats interesting, personally I would not find it useful.

I am unsure how I would implement it, I suppose you just create a logging appender that captures logs and then have those injected in the markdown, i guess you would reset the appender after processing each code block

I was thinking something like this in the users mdbook toml:
```toml
[book]
authors = ["mini_ninja_64"]
language = "en"
multilingual = false
src = "src"
title = "example"

[preprocessor.plantuml]
enable-logging = true
logging-config = "./logging_config.yml"
```

where logging_config.yml would be a log4rs config file
